--- Unit tests for issue command parsing
describe("commands.issue", function()
  local issue_cmd
  
  before_each(function()
    issue_cmd = require("gh.commands.issue")
  end)
  
  describe("completion", function()
    it("should complete subcommands", function()
      local completions = issue_cmd.complete("", { "" })
      assert.is_true(vim.tbl_contains(completions, "list"))
      assert.is_true(vim.tbl_contains(completions, "view"))
      assert.is_true(vim.tbl_contains(completions, "create"))
    end)
    
    it("should filter subcommands by prefix", function()
      local completions = issue_cmd.complete("cr", { "cr" })
      assert.is_true(vim.tbl_contains(completions, "create"))
      assert.is_false(vim.tbl_contains(completions, "list"))
    end)
    
    it("should complete partial subcommand 'c'", function()
      local completions = issue_cmd.complete("c", { "c" })
      assert.is_not_nil(completions)
      assert.is_true(#completions > 0)
      assert.is_true(vim.tbl_contains(completions, "create"))
      assert.is_true(vim.tbl_contains(completions, "close"))
      assert.is_false(vim.tbl_contains(completions, "list"))
    end)
    
    it("should complete list flags", function()
      local completions = issue_cmd.complete("--", { "list", "--" })
      assert.is_true(vim.tbl_contains(completions, "--state"))
      assert.is_true(vim.tbl_contains(completions, "--limit"))
      assert.is_true(vim.tbl_contains(completions, "--repo"))
    end)
    
    it("should complete state values", function()
      local completions = issue_cmd.complete("", { "list", "--state" })
      assert.is_true(vim.tbl_contains(completions, "open"))
      assert.is_true(vim.tbl_contains(completions, "closed"))
      assert.is_true(vim.tbl_contains(completions, "all"))
    end)
    
    it("should complete create flags", function()
      local completions = issue_cmd.complete("--", { "create", "--" })
      assert.is_true(vim.tbl_contains(completions, "--title"))
      assert.is_true(vim.tbl_contains(completions, "--assignee"))
      assert.is_true(vim.tbl_contains(completions, "--label"))
      assert.is_true(vim.tbl_contains(completions, "--template"))
    end)
    
    it("should return @me for assignee completion", function()
      local completions = issue_cmd.complete("", { "create", "--assignee" })
      assert.is_true(vim.tbl_contains(completions, "@me"))
    end)
  end)
end)
